development:
  user: fedoraAdmin
  password: fedoraAdmin
<<<<<<< HEAD
  url: <%= ENV['FEDORA_URL'] || "http://localhost:8080/fedora/rest" %>
  base_path: /njaffer-dev
=======
  url: http://localhost:8080/fedora/rest
  base_path: /njaffer-dev
>>>>>>> browse-everything with redirect URI problem
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8983/fedora/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora/rest
  base_path: /prod
